export const categoryMeta = {
  fruit: {
    name: "鲜果茶",
    short: "果",
    mood: "清爽醒脑",
    color: "#b8dc72",
    ink: "#30552b",
    image: "/assets/fruit-tea.png",
    note: "绿妍与当季鲜果的轻快组合",
  },
  special: {
    name: "茶特调",
    short: "调",
    mood: "灵感出逃",
    color: "#f6a5a2",
    ink: "#682f35",
    image: "/assets/tea-special.png",
    note: "茶香、果汁和云顶的大胆拼贴",
  },
  milk: {
    name: "牛乳茶",
    short: "乳",
    mood: "奶香治愈",
    color: "#d5ac71",
    ink: "#593d27",
    image: "/assets/milk-tea.png",
    note: "花香茶底遇见醇厚牛乳",
  },
  zero: {
    name: "0 咖乳饮",
    short: "眠",
    mood: "晚间放松",
    color: "#cbbbe6",
    ink: "#473d67",
    image: "/assets/zero-caffeine.png",
    note: "不含茶底的牛乳 / 椰乳方向",
  },
  cocoa: {
    name: "苦巧",
    short: "巧",
    mood: "甜酷充电",
    color: "#916047",
    ink: "#fff4d6",
    image: "/assets/cocoa.png",
    note: "浓郁可可和苦巧云顶的满足感",
  },
};

export const recipes = [
  {
    id: "green-mango-grape",
    name: "青提芒芒晴空",
    category: "fruit",
    source: "官方抄作业",
    sourceTone: "official",
    tags: ["清爽", "有果肉", "低负担"],
    summary: "绿妍打底，芒果负责明亮，青提把清爽感拉满。",
    layers: ["绿妍茶底", "芒果汁", "青提鲜果", "芝芝云顶", "0 脂脆波波"],
    temperature: "正常冰",
    sweetness: "不另外加糖",
    tip: "到店可直接打开喜茶小程序的「DIY 专属喜茶」，按顺序选择。",
    orderLine: "鲜果茶｜绿妍＋芒果汁＋青提＋芝芝云顶＋0脂脆波波｜不另外加糖｜正常冰",
  },
  {
    id: "qilan-grape-guava",
    name: "紫气东来",
    category: "special",
    source: "官方抄作业",
    sourceTone: "official",
    tags: ["葡萄", "花香", "弹弹"],
    summary: "花香奇兰接住葡萄的圆润，芭乐云顶带一点俏皮热带感。",
    layers: ["花香奇兰", "葡萄汁", "芭乐云顶", "弹弹冻"],
    temperature: "正常冰",
    sweetness: "少少甜",
    tip: "先尝一口再搅匀，能喝到茶香与云顶两段不同的风味。",
    orderLine: "茶特调｜花香奇兰＋葡萄汁＋芭乐云顶＋弹弹冻｜少少甜｜正常冰",
  },
  {
    id: "qilan-apple-guava",
    name: "青衣红袖",
    category: "special",
    source: "官方抄作业",
    sourceTone: "official",
    tags: ["青提苹果", "红柚", "花果香"],
    summary: "花香奇兰像一条青线，串起苹果青提与红柚的酸甜。",
    layers: ["花香奇兰", "羽衣苹果青提汁", "芭乐云顶", "红柚果粒"],
    temperature: "少冰",
    sweetness: "少少甜",
    tip: "怕酸可以保留少少甜；果粒款建议拿到后尽快喝。",
    orderLine: "茶特调｜花香奇兰＋羽衣苹果青提汁＋芭乐云顶＋红柚果粒｜少少甜｜少冰",
  },
  {
    id: "cocoa-yanhong",
    name: "可可深呼吸",
    category: "cocoa",
    source: "官方抄作业",
    sourceTone: "official",
    tags: ["浓郁", "苦甜", "醇厚"],
    summary: "嫣红的茶感托住可可，苦巧云顶把甜度收得很漂亮。",
    layers: ["可可", "嫣红茶底", "源牧 3.8 牛乳", "苦巧云顶"],
    temperature: "少冰",
    sweetness: "少少甜",
    tip: "喜欢茶感明显就先别搅云顶，分层喝更有变化。",
    orderLine: "苦巧｜可可＋嫣红＋源牧3.8牛乳＋苦巧云顶｜少少甜｜少冰",
  },
  {
    id: "qilan-milk-boba",
    name: "奇兰软绵绵",
    category: "milk",
    source: "公开实测",
    sourceTone: "tested",
    tags: ["奶香", "黑糖波波", "新手友好"],
    summary: "花香奇兰的焙火香，和厚牛乳、黑糖波波很合拍。",
    layers: ["花香奇兰", "厚牛乳", "黑糖波波", "轻芝芝云顶"],
    temperature: "少冰",
    sweetness: "少少甜",
    tip: "黑糖波波本身有甜味，少少甜会更耐喝。",
    orderLine: "牛乳茶｜花香奇兰＋厚牛乳＋黑糖波波＋轻芝芝云顶｜少少甜｜少冰",
  },
  {
    id: "qilan-mango-burst",
    name: "青芒奇遇",
    category: "fruit",
    source: "公开实测",
    sourceTone: "tested",
    tags: ["冰沙", "芒果", "脆波波"],
    summary: "绵密芒果冰沙里藏着青提和脆波波，口感很有戏。",
    layers: ["花香奇兰", "芒果汁", "青提鲜果", "0 脂脆波波"],
    temperature: "冰沙",
    sweetness: "不另外加糖",
    tip: "这杯靠水果自然甜，适合想喝果味又怕腻的时候。",
    orderLine: "鲜果茶｜花香奇兰＋芒果汁＋青提＋0脂脆波波｜不另外加糖｜冰沙",
  },
  {
    id: "green-guava-light",
    name: "芭乐轻轻",
    category: "fruit",
    source: "公开实测",
    sourceTone: "tested",
    tags: ["轻盈", "芭乐", "无额外糖"],
    summary: "极简三件套，绿妍清香、芭乐热带、脆波波活泼。",
    layers: ["绿妍茶底", "芭乐汁", "0 脂脆波波"],
    temperature: "少冰",
    sweetness: "不另外加糖",
    tip: "想更有层次，可到当日页面看看是否开放红柚果粒。",
    orderLine: "鲜果茶｜绿妍＋芭乐汁＋0脂脆波波｜不另外加糖｜少冰",
  },
  {
    id: "grape-sago-cloud",
    name: "葡萄落日",
    category: "special",
    source: "公开实测",
    sourceTone: "tested",
    tags: ["葡萄果肉", "西米", "芭乐云顶"],
    summary: "紫葡萄、白西米和粉色云顶，像一杯可以喝的落日。",
    layers: ["葡萄汁", "葡萄果肉", "西米", "芭乐云顶"],
    temperature: "冰沙",
    sweetness: "不另外加糖",
    tip: "果汁和果肉已有甜度，不另外加糖会更清亮。",
    orderLine: "茶特调｜葡萄汁＋葡萄果肉＋西米＋芭乐云顶｜不另外加糖｜冰沙",
  },
  {
    id: "cocoa-puer-boba",
    name: "碎银可可夜",
    category: "cocoa",
    source: "公开实测",
    sourceTone: "tested",
    tags: ["普洱", "黑糖", "重口满足"],
    summary: "碎银子普洱的陈香，把可可与黑糖波波拉回成熟风味。",
    layers: ["可可", "碎银子普洱", "黑糖波波", "苦抹云顶"],
    temperature: "少冰",
    sweetness: "少少甜",
    tip: "风味浓度高，建议不要再额外叠加小料。",
    orderLine: "苦巧｜可可＋碎银子普洱＋黑糖波波＋苦抹云顶｜少少甜｜少冰",
  },
  {
    id: "coconut-grape-zero",
    name: "月光葡萄椰",
    category: "zero",
    source: "灵感实验款",
    sourceTone: "idea",
    tags: ["0 咖方向", "椰乳", "晚间友好"],
    summary: "用椰乳的柔软包住葡萄与西米，适合晚上也想喝一杯。",
    layers: ["0 咖椰乳基底", "葡萄汁", "葡萄果肉", "西米"],
    temperature: "少冰",
    sweetness: "不另外加糖",
    tip: "0 咖分类的放行原料可能随门店变化，请以小程序当日可选项为准。",
    orderLine: "牛乳/椰乳0咖｜椰乳基底＋葡萄汁＋葡萄果肉＋西米｜不另外加糖｜少冰",
  },
  {
    id: "coconut-guava-zero",
    name: "芭乐晚安云",
    category: "zero",
    source: "灵感实验款",
    sourceTone: "idea",
    tags: ["0 咖方向", "芭乐", "柔和"],
    summary: "椰乳与芭乐走柔和路线，再用弹弹冻添一点小惊喜。",
    layers: ["0 咖椰乳基底", "芭乐汁", "弹弹冻", "芭乐云顶"],
    temperature: "去冰",
    sweetness: "少少甜",
    tip: "如果门店页面未放行芭乐云顶，去掉云顶也成立。",
    orderLine: "牛乳/椰乳0咖｜椰乳基底＋芭乐汁＋弹弹冻＋芭乐云顶｜少少甜｜去冰",
  },
  {
    id: "milk-yanhong-sago",
    name: "嫣红西米露",
    category: "milk",
    source: "灵感实验款",
    sourceTone: "idea",
    tags: ["茶香", "西米", "顺滑"],
    summary: "嫣红的熟果香配鲜牛乳，西米让尾韵变得软糯。",
    layers: ["嫣红茶底", "源牧 3.8 牛乳", "西米", "轻芝芝云顶"],
    temperature: "去冰",
    sweetness: "少少甜",
    tip: "如果想突出茶感，可以去掉云顶并保留少少甜。",
    orderLine: "牛乳茶｜嫣红＋源牧3.8牛乳＋西米＋轻芝芝云顶｜少少甜｜去冰",
  },
];

export const sources = [
  {
    label: "喜茶官网",
    detail: "品牌与门店信息入口",
    url: "https://www.heytea.com/",
  },
  {
    label: "喜茶官方微博推荐",
    detail: "2026-07-10 公布的 4 款 DIY 抄作业配方",
    url: "https://www.sina.cn/news/detail/5319212505239044.html",
  },
  {
    label: "深圳新闻网",
    detail: "DIY 五大品类、操作路径与公开原料说明",
    url: "https://www.sznews.com/news/content/2026-07/06/content_32112920.htm",
  },
  {
    label: "喜茶 DIY 全国上线报道",
    detail: "鲜果茶可选茶底、果汁、鲜果、小料与云顶范围",
    url: "https://finance.sina.com.cn/roll/2026-07-04/doc-inifrpaa0027108.shtml",
  },
  {
    label: "北京地区公开实测",
    detail: "6 款用户实测组合与甜度建议",
    url: "https://www.sohu.com/a/1047889911_121124449",
  },
];
